version: "3"

services:  
    api:
        container_name: api
        image: nginx:latest
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./api:/api
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    client:
        container_name: client
        image: node:latest
        command: bash -c "npm install && npm run serve"
        restart: always
        ports:
            - "8080:8080"
        working_dir: /todo
        volumes:
            - ./todo:/todo
    php-fpm:
        container_name: php-fpm
        command: bash -c "composer install --working-dir=/api --no-cache && php-fpm -F"
        build:
            context: .
            dockerfile: ./.docker/php-fpm/Dockerfile
        restart: always
        volumes:
            - ./api:/api
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog:latest
        ports:
          - "8025:8025"
    db:
        container_name: db
        image: mariadb:10.5.8
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_hungarian_ci
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: todos
            MYSQL_USER: root
        volumes:
            - ./.docker/db/:/docker-entrypoint-initdb.d
            - ./.docker/db:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:latest
        restart: always
        ports:
            - "8001:80"
        depends_on:
            - db
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=123456